name: Build for Windows

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn tensorflow matplotlib pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed wind_forecast_app.py

    - name: Upload artifact
      uses: actions/upload-artifact@4
      with:
        name: wind_forecast_app
        path: dist/wind_forecast_app.exe